# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  URL_NETCDF_WIN: https://downloads.unidata.ucar.edu/netcdf-c/4.9.2/netCDF4.9.2-NC4-64.exe
permissions:
  id-token: write
jobs:
  build:

    runs-on: ubuntu-latest

    env:
      EXEKIAS_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      EXEKIAS_RESOURCEGROUP: exekias-canary-github-linux
      EXEKIAS_STORAGEACCOUNT: exekiascanaryghl

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Install NetCDF and bicep compiler
      run: |
        sudo apt update
        sudo apt install libnetcdf-dev -y
        curl --no-progress-meter -Lo ${{ runner.temp }}/bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
        chmod +x ${{ runner.temp }}/bicep


    - name: Download NetCDF-win
      shell: pwsh
      run: |
        Invoke-WebRequest $env:URL_NETCDF_WIN -OutFile ${{ runner.temp }}/netcdf.exe
        7z x ${{ runner.temp }}/netcdf.exe bin/*.dll -o${{ runner.temp }} -y
        Get-ChildItem ${{ runner.temp }}\bin
    - name: Build
      run: |
        dotnet publish src/exekias -c Release
      env:
        BicepPath: ${{ runner.temp }}/bicep
        LIBNETCDFPATH: ${{ runner.temp }}/bin/netcdf.dll
    - name: Start azurite
      shell: bash
      run: |
        npm install -g azurite
        azurite --silent --location ${{ runner.temp }}/azurite --debug ${{ runner.temp }}/azurite.log --blobHost &
    - name: Test
      run: |
        dotnet test --verbosity normal src/Exekias.Core.Tests
        dotnet test --verbosity normal src/Exekias.SDS.Tests
        dotnet test --verbosity normal src/Exekias.AzureStorageEmulator.Tests
    - name: Login via Az module
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
    - name: Run canary test
      uses: azure/powershell@v1
      with:
          inlineScript: |
            ./exekias-canary-test.ps1
          azPSVersion: "latest"
      env:
        EXEKIAS_BIN: src/exekias/bin/Release/net6.0/publish/exekias