name: Build and upload release binaries
on:
  release:
    types: [created]
env:
  URL_NETCDF_WIN: https://downloads.unidata.ucar.edu/netcdf-c/4.9.2/netCDF4.9.2-NC4-64.exe
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install Bicep
        run: |
          curl --no-progress-meter -Lo ${{ runner.temp }}/bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          chmod +x ${{ runner.temp }}/bicep
          echo "BicepPath=${{ runner.temp }}/bicep" >> $GITHUB_ENV
      - name: Download NetCDF
        shell: pwsh
        run: |
          Invoke-WebRequest $env:URL_NETCDF_WIN -OutFile ${{ runner.temp }}/netcdf.exe
          7z x ${{ runner.temp }}/netcdf.exe bin/*.dll -o${{ runner.temp }} -y
          Get-ChildItem ${{ runner.temp }}/bin
      - name: Build
        run: |
          dotnet publish src/exekias --configuration Release --self-contained --runtime win-x64 --output publish/win-x64
          pushd publish/win-x64
          7z a -bd $GITHUB_WORKSPACE/exekias.cli.win-x64.zip .
          popd
          dotnet publish src/exekias --configuration Release --self-contained --runtime linux-x64 --output publish/linux-x64
          pushd publish/linux-x64
          7z a -bd $GITHUB_WORKSPACE/exekias.cli.linux-x64.zip .
          popd
        env:
          LIBNETCDFPATH: ${{ runner.temp }}/bin/netcdf.dll
      - name: Upload windows cli
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./exekias.cli.win-x64.zip
          asset_name: exekias.cli.win-x64.zip
          asset_content_type: application/zip
      - name: Upload linux cli
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./exekias.cli.linux-x64.zip
          asset_name: exekias.cli.linux-x64.zip
          asset_content_type: application/zip
